name: yajudge_master
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  yajudge_common:
    path: ../yajudge_common
  tuple: ^2.0.0
  fixnum: ^1.0.1
  logging: ^1.0.2
  args: ^2.3.1
  path: ^1.8.2
  grpc: ^3.0.2
  protobuf: ^2.0.1
  postgres: ^2.4.3
  crypto: ^3.0.2
  xml: ^6.0.1
  posix: ^3.1.0

dev_dependencies:
  lints: ^2.0.0