name: yajudge_master
publish_to: 'none'

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  yajudge_common:
    path: ../yajudge_common
  tuple: ^2.0.0
  fixnum: ^1.0.0
  logging: ^1.0.2
  args: ^2.3.0
  path: ^1.8.0
  grpc: ^3.0.2
  postgres: ^2.4.3
  crypto: ^3.0.1
  xml: ^5.3.1
