service:
  # NOTE: service configuration has less priority than command-line arguments
  log_file: '@LOGS_DIRECTORY/grader-$NAME.log'     # /var/log/yajudge/grader-default.log or /opt/yajudge/log/grader-default.log
  pid_file: '@RUNTIME_DIRECTORY/grader-$NAME.pid'  # /run/yajudge/grader-default.pid or /opt/yajudge/pid/grader-default.log
  systemd_slice: 'yajudge-grader'  # has effect only while starting via 'yajudge-grader start' command

rpc:
  host: localhost
  port: 9095

  # private token must be stored in separate file not readable by random user
  private_token_file: '@CONFIGURATION_DIRECTORY/private-token.txt'  # /etc/yajudge/private-token.txt

locations:
  system_environment: '@SYSTEM_DIR'                    # /var/lib/yajudge/system or /opt/yajudge/system
  working_directory: '@WORK_DIR/$NAME'                 # /var/lib/yajudge/work/default or /opt/yajudge/work/default
  cache_directory: '@CACHE_DIRECTORY/$NAME'            # /var/cache/yajudge/default or /opt/yajudge/cache/default


jobs:
  arch_specific_only: false  # set to 'true' if grader is supplementary, for example if running on slow Raspberry Pi,
                             # to prevent taking generic problem jobs which better to run on more powerful servers

default_build_properties:
  c:
    compiler: clang
    compile_options: -O2 -g -Werror
    enable_sanitizers: undefined address
  cxx:
    compiler: clang++
    compile_options: -02 -g -Werror
    enable_sanitizers: undefined address
  S:
    compiler: clang
    compile_options: -O0 -g
  java:
    compiler: javac
    compile_options: -g -Werror -source 11 -target 11

default_runtime_properties:
  valgrind:
    executable: valgrind
    runtime_options: --leak-check=full --show-leak-kinds=all --track-origins=yes
    extra_memory_limit: 16
    cpu_time_scale: 2.0
  java:
    executable: java
    runtime_options: -enableassertions
    extra_memory_limit: 256

default_limits:
  stack_size_limit_mb: 4
  memory_max_limit_mb: 64
  cpu_time_limit_sec: 1
  real_time_limit_sec: 5
  proc_count_limit: 20
  fd_count_limit: 20
  stdout_size_limit_mb: 1
  stderr_size_limit_mb: 1
  allow_network: false

default_security_context:
  forbidden_functions: fork clone kill unlink chroot
