rpc:
  endpoints: '@YAJUDGE_HOME/conf/@CONFIG_NAME/endpoints.yaml'
  # private token must be stored in separate file not readable by random user
  private_token_file: '@YAJUDGE_HOME/conf/@CONFIG_NAME/private-token.txt'

locations:
  system_environment: '@YAJUDGE_HOME/system'
  working_directory: '@YAJUDGE_HOME/work/@CONFIG_NAME'
  cache_directory: '@YAJUDGE_HOME/cache/@CONFIG_NAME'


jobs:
  arch_specific_only: false  # set to 'true' if grader is supplementary, for example if running on slow Raspberry Pi,
                             # to prevent taking generic problem jobs which better to run on more powerful servers

default_build_properties:
  c:
    compiler: clang
    compile_options: -O2 -g -Werror
    enable_sanitizers: undefined address
  cxx:
    compiler: clang++
    compile_options: -02 -g -Werror
    enable_sanitizers: undefined address
  S:
    compiler: clang
    compile_options: -O0 -g
  java:
    compiler: javac
    compile_options: -g -Werror

default_runtime_properties:
  valgrind:
    executable: valgrind
    runtime_options: --leak-check=full --show-leak-kinds=all --track-origins=yes
    extra_memory_limit: 16
    cpu_time_scale: 2.0
  java:
    executable: java
    runtime_options: -enableassertions
    extra_memory_limit: 256

default_limits:
  stack_size_limit_mb: 4
  memory_max_limit_mb: 64
  cpu_time_limit_sec: 1
  real_time_limit_sec: 5
  proc_count_limit: 20
  fd_count_limit: 20
  stdout_size_limit_mb: 1
  stderr_size_limit_mb: 1
  allow_network: false

default_security_context:
  forbidden_functions: fork clone kill unlink chroot
