name: yajudge_client
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  yajudge_common:
    path: ../yajudge_common
  fixnum: ^1.0.1
  grpc: ^3.0.2
  yaml: ^3.1.0
  yaml_writer: ^1.0.1
  visibility_detector: ^0.3.3
  ffi: ^1.1.2
  archive: ^3.1.2
  universal_html: ^2.0.8
  intl: ^0.17.0
  url_launcher: ^6.0.9
  logging: ^1.0.2
  tuple: ^2.0.0
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_treeview: ^1.0.4+1
  flutter_markdown: ^0.6.2
  google_fonts: ^3.0.0
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.1.7
  lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: PT Mono
      fonts:
        - asset: fonts/PTMono-Regular.ttf
    - family: PT Sans
      fonts:
        - asset: fonts/PTSans-Regular.ttf
        - asset: fonts/PTSans-Bold.ttf
          weight: 700
        - asset: fonts/PTSans-Italic.ttf
          style: italic
        - asset: fonts/PTSans-BoldItalic.ttf
          style: italic
          weight: 700
    - family: PT Sans Caption
      fonts:
        - asset: fonts/PTSansCaption-Regular.ttf
        - asset: fonts/PTSansCaption-Bold.ttf
          weight: 700


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
