name: yajudge_grader
publish_to: 'none'

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  yajudge_common:
    path: ../yajudge_common
  fixnum: ^1.0.0
  logging: ^1.0.2
  args: ^2.3.0
  path: ^1.8.0
  grpc: ^3.0.2


