name: yajudge_grader
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  yajudge_common:
    path: ../yajudge_common
  fixnum: ^1.0.1
  logging: ^1.0.2
  args: ^2.3.1
  path: ^1.8.2
  grpc: ^3.0.2
  posix: ^3.1.0
  tuple: ^2.0.0
  crypto: ^3.0.2
  yaml: ^3.1.1
  protobuf: ^2.0.1

dev_dependencies:
  lints: ^2.0.0

