name: yajudge_common
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  grpc: ^3.0.2
  yaml: ^3.1.0
  path: ">=1.8.1"
  protobuf: ^2.0.1
  fixnum: ^1.0.1
  archive: ^3.3.0
  bson: ^1.0.4
  tuple: ^2.0.0
  xml: ^6.0.1
  posix: ^3.1.0
  encrypt: ^5.0.1
  crypto: ^3.0.2
  hex: ^0.2.0


dev_dependencies:
  build_runner: ^2.1.7
  lints: ^2.0.0
