name: yajudge_common
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  grpc: ^3.0.2
  yaml: ^3.1.0
  path: ">=1.8.0"


dev_dependencies:
  build_runner: ^2.1.7
  lints: ^2.0.0
